# Generated by Django 5.1 on 2024-08-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='Image')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('category', models.CharField(choices=[('tech', 'Техника'), ('cars', 'Машины'), ('sport', 'Спортивное'), ('homes', 'Недвижимость'), ('other', 'Другое')], max_length=50, verbose_name='Категория')),
                ('status', models.CharField(choices=[('moderation', 'На модерации'), ('accepted', 'Опубликовано'), ('rejected', 'Отклонено'), ('deleted', 'На удаление')], max_length=50, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('publicate_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
